pipeline {
    agent any

    stages {
        stage('Get Project') {
            steps {
                git branch: 'master', url: 'https://github.com/ItsLukio/tester4petitions.git'
            }
        }
        stage('Debug Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }
        stage('Set Permissions') {
            steps {
                sh 'chmod +x tester4petitions/mvnw'
            }
        }
        stage('Build') {
            steps {
                sh 'cd tester4petitions && mvn clean:clean'
                sh 'cd tester4petitions && mvn dependency:copy-dependencies'
                sh 'cd tester4petitions && mvn compiler:compile'
    }
}
        stage('Test') {
            steps {
                sh 'cd tester4petitions && mvn test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
        }
    }
}
        stage('Package') {
            steps {
                sh 'cd tester4petitions && ./mvnw package'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/tester4petitions*.war', allowEmptyArchive: true
        }
    }
       stage ('Deploy')
        {
            steps {
                sh 'docker build -f Dockerfile -t myapp . '
                sh 'docker rm -f "myappcontainer" || true'
                sh 'docker run --name "myappcontainer" -p 8081:8080 --detach myapp:latest'
            }
        }
}
