pipeline {
    agent any

    stages {
        stage('Get Project') {
            steps {
                git branch: 'master', url: 'https://github.com/ItsLukio/tester4petitions.git'
            }
        }
        stage('Debug Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }
        stage('Build') {
            steps {
                sh 'cd tester4petitions && mvn clean:clean'
                sh 'cd tester4petitions && mvn dependency:copy-dependencies'
                sh 'cd tester4petitions && mvn compiler:compile'
    }
}
        stage('Test') {
            steps {
                sh 'make check || true'
                junit '**/target/*.xml'
            }
        }
        stage('Package') {
            steps {
                sh './mvnw package'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }
    }
}
