pipeline {
	agent any

	stages {
    	stage ('GetProject') {
        	steps {
            	git 'https://github.com/ItsLukio/tester4petitions.git'
        	}
    	}
    	stage ('build') {
        	steps {
            	sh 'mvn clean:clean'
            	sh 'mvn dependency:copy-dependencies'
            	sh 'mvn compiler:compile'
        	}
    	}
    	stage('Test') {
        	steps {
            	sh 'make check || true'
            	junit '**/target/*.xml'
        	}
    	}
	}
}
    	stage ('Package') {
        	steps {
            	sh 'mvn package'
        	}
    	}
	}
	post {
    	success {
        	archiveArtifacts allowEmptyArchive: true,
            	artifacts: '**/SpringBootTest*.jar'
    	}
	}
}
